//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MVC3_DBfirst.Models
{
    public partial class Blog
    {
        public Blog()
        {
            this.Posts = new HashSet<Post>();
        }
    
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string BloggerName { get; set; }
    
        public virtual ICollection<Post> Posts { get; set; }
    }
    
}
